site_name: Carteira Digital Trânsito

theme:
  name: material
  language: pt
  logo: assets/logos/logo.png
  favicon: assets/logos/favicon.ico

extra_css:
    - stylesheets/extra.css

repo_url: https://github.com/Requisitos-de-Software/2020.2-CarteiraDigitalTransito

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Pré-rastreabilidade:
      - Rich pictures: pre_rastreabilidade/rich_pictures.md
  - Elicitação de requisitos:
      - Personas: elicitacao/personas.md
      - Introspecção: elicitacao/introspeccao.md
      - Questionário: elicitacao/questionario.md
      - Brainstorming: elicitacao/brainstorming.md
      - Todos os requisitos: elicitacao/requisitos.md
  - Priorização de requisitos:
      - First Things First: priorizacao/first_thing_first.md
      - MoSCoW: priorizacao/moscow.md
  - Modelagem:
      - Casos de uso: modelagem/caso_de_uso.md
      - Cenários: modelagem/cenarios.md
      - Léxico: modelagem/lexico.md
      - Especificação suplementar: modelagem/especificacao_suplementar.md
      - NFR Framework: modelagem/nfr_framework.md
      - Backlog do produto: modelagem/backlog_do_produto.md
      - Histórias de Usuário: modelagem/historia_de_usuario.md
  - Análise:
    - Verificação:
        - Planejamento: analise/verificacao/planejamento.md
        - Rich pictures: analise/verificacao/rich_picture.md
        - Casos de Uso: analise/verificacao/caso_de_uso.md
        - Cenários: analise/verificacao/cenario.md
        - Léxicos: analise/verificacao/lexico.md
        - NFR Framework: analise/verificacao/nfr_framework.md
        - Backlog de Produto: analise/verificacao/backlog.md
    - Validação:
        - Informal: analise/validacao/informal.md
        - Protótipo: analise/validacao/prototipo.md
        - Viewpoint: analise/validacao/viewpoint.md
  - Pós rastreabilidade:
    - Matriz Forward-From: pos_rastreabilidade/foward_from.md
    - Matriz Backward-From: pos_rastreabilidade/backward_from.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao_1.md
    - Apresentação 2: apresentacoes/apresentacao_2.md
    - Apresentação 3: apresentacoes/apresentacao_3.md
    - Apresentação 4: apresentacoes/apresentacao_4.md
    - Apresentação 5: apresentacoes/apresentacao_5.md
    - Apresentação 6: apresentacoes/apresentacao_6.md
    - Apresentação 7: apresentacoes/apresentacao_7.md
  - Atas:
    - 26/02/2021: atas/reuniao-26-02-2021.md
    - 11/03/2021: atas/reuniao-11-03-2021.md
    - 15/03/2021: atas/reuniao-15-03-2021.md
    - 23/03/2021: atas/reuniao-23-03-2021.md
    - 05/04/2021: atas/reuniao-05-04-2021.md
